# Generated by Django 5.1.6 on 2025-03-06 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
