# Generated by Django 5.1.6 on 2025-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='pop',
            field=models.BooleanField(default=False),
        ),
    ]
