# Generated by Django 5.1.6 on 2025-03-09 16:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_sliders_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='dynamic/images/')),
                ('files', models.FileField(upload_to='dynamic/files/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
