# Generated by Django 5.1.6 on 2025-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contentType',
        ),
        migrations.AddField(
            model_name='notices',
            name='noticeBody',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ContentTypes',
        ),
    ]
