# Generated by Django 5.1.6 on 2025-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_menu_viewref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='document',
            field=models.FileField(upload_to='notices/'),
        ),
    ]
