# Generated by Django 5.1.6 on 2025-03-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_notices_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='viewRef',
            field=models.CharField(default='front.views.dynamicView', max_length=100),
        ),
    ]
