# Generated by Django 5.1.6 on 2025-03-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_dynamic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='slug',
            new_name='path',
        ),
    ]
