# Generated by Django 5.1.6 on 2025-03-04 10:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_notices_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='noticeBody',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
