# Generated by Django 5.1.6 on 2025-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_menu_viewref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='viewRef',
            field=models.CharField(max_length=100),
        ),
    ]
