# Generated by Django 5.1.6 on 2025-03-04 10:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_notices_noticebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='noticeBody',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
