# Generated by Django 5.1.6 on 2025-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_menu_viewref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_en', models.DateField()),
                ('date_np', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=200)),
            ],
        ),
    ]
