# Generated by Django 5.1.6 on 2025-03-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='notices/documents/')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.notices')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notices/images/')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.notices')),
            ],
        ),
    ]
