# Generated by Django 5.1.6 on 2025-03-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_noticedocuments_noticeimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='document',
        ),
    ]
