# Generated by Django 5.1.6 on 2025-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_remove_notices_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticedocuments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notices/documents/'),
        ),
        migrations.AlterField(
            model_name='noticeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/images/'),
        ),
    ]
