# Generated by Django 5.1.6 on 2025-03-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_alter_noticedocuments_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='dynamic/files/'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic/images/'),
        ),
    ]
