# Generated by Django 5.1.6 on 2025-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_rename_noticebody_notices_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='files',
            new_name='document',
        ),
    ]
